Repository lsalazar1/pvPark, pull requests merged in 2020-02, with the labels that each got.

#27 Test Data Created
  CODEOWNERS
  TestData/AllEmpty.json
  TestData/AllFull.json
  TestData/Mixed.json
  routes/apis/users.js
Labels: enhancement

#30 Hot Fix: Successful Response with Encrypted password
  routes/apis/users.js
Labels: bug

#35 Backend Related Fixes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  TestData/testLot.json
  config/db.js
  models/SrCollins.js
  package-lock.json
  package.json
  python/ParkingLot.py
  routes/apis/srcollins.js
  server.js
Labels: enhancement

#47 Issue 36
  models/BusinessAG.js
  models/MSC.js
  models/Rasp.js
  routes/apis/businessag.js
  routes/apis/msc.js
  routes/apis/rasp.js
  server.js
  test.js
Labels: enhancement

#53 Thinking man
  .gitignore
  config/default.json
  models/Rasp.js
  python/ParkingLot.py
  python/main.py
  routes/apis/rasp.js
  server.js
Labels: enhancement

#60 Frontend
  .DS_Store
  iOS App/.DS_Store
  iOS App/iOS Frontend/.DS_Store
  iOS App/iOS Frontend/App Testing.xcodeproj/project.pbxproj
  iOS App/iOS Frontend/App Testing.xcodeproj/project.xcworkspace/xcuserdata/reneouoba.xcuserdatad/UserInterfaceState.xcuserstate
  iOS App/iOS Frontend/App Testing/.DS_Store
  iOS App/iOS Frontend/App Testing/Assets.xcassets/.DS_Store
  iOS App/iOS Frontend/App Testing/Base.lproj/Main.storyboard
  iOS App/iOS Frontend/App Testing/HomeViewController.swift
  iOS App/iOS Frontend/App Testing/MSCViewController.swift
  iOS App/iOS Frontend/App Testing/Media/asphalt_srCollins.jpg
  iOS App/iOS Frontend/App Testing/Media/groundQuad1.jpg
  iOS App/iOS Frontend/App Testing/Media/groundTextureMSC.jpg
  iOS App/iOS Frontend/App Testing/lot.swift
  iOS App/iOS Frontend/App Testing/mscQuad1ViewController.swift
  iOS App/iOS Frontend/App Testing/mscQuad4ViewController.swift
  iOS App/iOS Frontend/App Testing/sensor.swift
  iOS App/iOS Frontend/App Testing/srCollinsViewController.swift
  routes/.DS_Store
Labels: backend, enhancement, frontend

#61 Development
  .DS_Store
  iOS App/.DS_Store
  iOS App/iOS Frontend/.DS_Store
  iOS App/iOS Frontend/App Testing.xcodeproj/project.pbxproj
  iOS App/iOS Frontend/App Testing.xcodeproj/project.xcworkspace/xcuserdata/reneouoba.xcuserdatad/UserInterfaceState.xcuserstate
  iOS App/iOS Frontend/App Testing/.DS_Store
  iOS App/iOS Frontend/App Testing/Assets.xcassets/.DS_Store
  iOS App/iOS Frontend/App Testing/Base.lproj/Main.storyboard
  iOS App/iOS Frontend/App Testing/HomeViewController.swift
  iOS App/iOS Frontend/App Testing/MSCViewController.swift
  iOS App/iOS Frontend/App Testing/Media/asphalt_srCollins.jpg
  iOS App/iOS Frontend/App Testing/Media/groundQuad1.jpg
  iOS App/iOS Frontend/App Testing/Media/groundTextureMSC.jpg
  iOS App/iOS Frontend/App Testing/lot.swift
  iOS App/iOS Frontend/App Testing/mscQuad1ViewController.swift
  iOS App/iOS Frontend/App Testing/mscQuad4ViewController.swift
  iOS App/iOS Frontend/App Testing/sensor.swift
  iOS App/iOS Frontend/App Testing/srCollinsViewController.swift
  routes/.DS_Store
  test.js
Labels: enhancement
